name: Despliegue prueba EC2

on:
  push:
    branches: 
    - develop

jobs:
  # tests:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout del código
  #       uses: actions/checkout@v4
  #     - name: Configurar Node.js
  #       uses: actions/setup-node@v4
  #     - name: Instalar dependencias
  #       run: npm install
  #     - name: Ejecutar Pruebas Unitarias
  #       run: npm run test
        
  deploy:
    # needs: tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
        
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias para JSDoc
        run: npm install

      - name: Generar Documentación JSDoc
        run: npm run docs
        continue-on-error: true

      - name: Verificar Secrets
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
        run: |
          if [ -z "$EC2_HOST" ]; then
            echo "::error::El secret EC2_HOST no está configurado en GitHub."
            exit 1
          fi
          if [ -z "$EC2_SSH_KEY" ]; then
            echo "::error::El secret EC2_SSH_KEY no está configurado en GitHub."
            exit 1
          fi
          if [ -z "$EC2_USERNAME" ]; then
            echo "::error::El secret EC2_USERNAME no está configurado en GitHub."
            exit 1
          fi
          echo "Todos los secrets necesarios están presentes."

      - name: Configurar directorio .ssh
        run: mkdir -p ~/.ssh/

      - name: Guardar clave privada
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Agregar host a known_hosts
        run: ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Preparar directorio en EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "sudo mkdir -p /var/www/html/pruebainstanciaec2 && sudo chown -R \$USER:\$USER /var/www/html/pruebainstanciaec2"

      - name: Despliegue de la Aplicación a EC2
        run: |
          rsync -avz --delete ./src/ ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/var/www/html/pruebainstanciaec2/
          rsync -avz --delete ./docs/ ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/var/www/html/pruebainstanciaec2/docs/